# Generated by Django 5.2.4 on 2025-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shablon_sportdiploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportdiploma',
            name='series',
            field=models.CharField(max_length=20),
        ),
    ]
